### ISSUE TITLE
Clarify behaviour when X-B3-Flags is set to 0

### ISSUE THREAD

**Issue by nonspecialist** [openzipkin/b3-propagation#20]
Referencing https://github.com/openzipkin/zipkin4net/issues/201#issuecomment-382572888

The specification doesn't currently define what should happen if `X-B3-Flags: 0` is received, only if `X-B3-Flags: 1` is received

**Comment by codefromthecrypt** [comment]
The only valid value is "1". We can clarify that other values are ignored
if you would like to know that malformed flags shouldn't break the trace

**Comment by codefromthecrypt** [comment]
See also https://github.com/openzipkin/b3-propagation/issues/21

**Comment by codefromthecrypt** [comment]
https://github.com/openzipkin/b3-propagation/pull/26 should have clarified this I hope
