### ISSUE TITLE
Move repository to https://github.com/apache/incubator-zipkin-b3-propagation

### ISSUE THREAD

**Issue by michaelsembwever** [openzipkin/b3-propagation#25]
As part of the move to the Apache Software Foundation this repository will transfer ownership to `apache` and name to `incubator-zipkin-b3-propagation`.

See https://issues.apache.org/jira/browse/INFRA-16989

**Comment by codefromthecrypt** [comment]
when this is merged, all tasks are done I think https://github.com/apache/incubator-zipkin-b3-propagation/pull/34

**Comment by basvanbeek** [comment]
closed: see https://github.com/openzipkin/zipkin/issues/2629
