### ISSUE TITLE
Customize ID generation for Span and Trace id.

### ISSUE THREAD

**Issue by nitin1706** [openzipkin/b3-propagation#27]
Can I customize the ID generated for Span and Trace? We are using a UID to identify a request and would like to use this as a trace id for my project. If its possible, How can I alter the traceID generation?

**Comment by jcchavezs** [comment]
According to [this](https://github.com/openzipkin/b3-propagation#identifiers):

> Trace identifiers are 64 or 128-bit, but all span identifiers within a trace are 64-bit. All identifiers are opaque.

So UUID (if that is the case) might not fit here.

In such cases where you want to correlate a trace with a generated ID you better go for a `tag` as it is possible to find a trace with that tag. Usually you tag the root span with a `requestID=my_id` and then search for it in zipkin ui.
