### ISSUE TITLE
Track support of 128 bit X-B3-TraceId

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/b3-propagation#6]
A 128-bit trace ID is when `X-B3-TraceId` has 32 hex characters as opposed to 16. For example, `X-B3-TraceId: 463ac35c9f6413ad48485a3953bb6124`.

Here are the status options for 128bit `X-B3-TraceId`:
* unsupported: 32 character trace ids will break the library
* downgrade: Read 32 character trace ids by throwing away the high bits (any characters left of 16 characters). This effectively downgrades the ID to 64 bits.
* transparent: Pass `X-B3-TraceId` through the system without interpreting it.
* supported:  Can start traces with 128-bit trace IDs, propagates and reports them as 128-bits
* epoch128: Can start traces with 128-bit trace IDs which are prefixed with epoch seconds

This is a list of zipkin libraries and their status in supporting 128-bit trace IDs

| library | version | status | notes |
| --- | --- | --- | --- |
| [zipkin-js](https://github.com/openzipkin/zipkin-js) | 0.5+ | supported | `new Tracer({..., traceId128Bit: true})` |
| [pyramid_zipkin](https://github.com/Yelp/pyramid_zipkin) | 0.16+ | downgrade | |
| [brave](https://github.com/openzipkin/brave) | 3.15+/4.9+ | supported/epoch128 | https://github.com/openzipkin/brave/tree/master/brave-core#128-bit-trace-ids |
| [spring-cloud-sleuth](https://github.com/spring-cloud/spring-cloud-sleuth) | 1.0.11+/1.2.6+ | supported/epoch128 | set `spring.sleuth.traceId128=true` |
| [finagle](https://github.com/twitter/finagle) | 0.40+ | downgrade | |
| [zipkin-ruby](https://github.com/openzipkin/zipkin-ruby)  |  | unsupported | depends on https://github.com/twitter/finagle/issues/565 |
| [ZipkinTracerModule](https://github.com/mdsol/Medidata.ZipkinTracerModule)  | 3.2+  | supported |  `Create128BitTraceId(true)` |
| [zipkin-go-opentracing](https://github.com/openzipkin/zipkin-go-opentracing) | 0.2+ | supported | https://godoc.org/github.com/openzipkin/zipkin-go-opentracing#TraceID128Bit |
| [akka-tracing](https://github.com/levkhomich/akka-tracing) | 0.5.2+ | downgrade | |
| [wingtips](https://github.com/Nike-Inc/wingtips) | 0.11.2+ | transparent | |
| [jaeger](https://github.com/uber/jaeger-client-java) | 0.10+ | downgrade | | 
| [zipkin4net](https://github.com/criteo/zipkin4net) | 0.4+ | supported | | 

### epoch128
When a trace ID is 128-bits and the first 32 bits are epoch seconds, the ID can be translated into
an Amazon Web Services ID. Tracers who do this can tunnel through ELBs, for example.

Here's an example implementation
```java
  static long nextTraceIdHigh(Random prng) {
    long epochSeconds = System.currentTimeMillis() / 1000;
    int random = prng.nextInt();
    return (epochSeconds & 0xffffffffL) << 32
        |  (random & 0xffffffffL);
  }
```

See openzipkin/zipkin#1754

**Comment by codefromthecrypt** [comment]
ps I'm clicking "check" when a pull request is raised, and noting the version, once released.

**Comment by basvanbeek** [comment]
@adriancole I've updated [zipkin-go-opentracing](https://github.com/openzipkin/zipkin-go-opentracing) to tolerate 128bit traceID's and have sent a PR to [monkit-zipkin](https://github.com/spacemonkeygo/monkit-zipkin). The other listed Go tracer [go-zipkin](https://github.com/elodina/go-zipkin) does not have B3 propagation and uses a custom Avro encoding over Kafka so we don't have to deal with them on this issue.

**Comment by codefromthecrypt** [comment]
thanks for the help @basvanbeek

**Comment by codefromthecrypt** [comment]
Ok, this phase is nearly complete. Almost all libraries have merged code, except akka and .net (cc @levkhomich @jcarres-mdsol)

I think this is close enough to start doing other work, such as supporting server-side effort

**Comment by codefromthecrypt** [comment]
side-note cloud foundry gorouter doesn't seem to interpret the X-B3-TraceId header, so doesn't seem to need any work here https://github.com/cloudfoundry/gorouter/blob/4d9497354baaf103310cc7c78a3fb5ccf69e6016/common/http/headers_test.go

**Comment by codefromthecrypt** [comment]
added this to support 128-bit traces in zipkin-js https://github.com/openzipkin/zipkin-js/pull/57

**Comment by codefromthecrypt** [comment]
Tracking moved here https://cwiki.apache.org/confluence/display/ZIPKIN/128-bit+Trace+ID
